### ISSUE TITLE
Generic Errors?

### ISSUE THREAD

**Issue by VaelophisNyx** [cheeeeeeeeeen/RoR2-ChensHelpers#3]
### Describe the Bug
No noticable effects from errors, but they do seem to be of note?

### Console Log
```
[Info   :   BepInEx] Loading [ChensGradiusMod 3.3.5]
[Error  : Unity Log] MissingMethodException: UnityEngine.Object Chen.Helpers.GeneralHelpers.AssetsManager.Register()
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

[Info   :   BepInEx] Loading [ChensMinionRetarget 1.0.7]
[Debug  :     R2API] Hook added by assembly: ChensMinionRetarget.dll for: RoR2.UI.PingIndicator.RebuildPing
[Debug  :     R2API] Hook added by assembly: ChensMinionRetarget.dll for: RoR2.CharacterAI.BaseAI.EvaluateSkillDrivers
[Debug  :     R2API] Hook added by assembly: ChensMinionRetarget.dll for: RoR2.CharacterAI.BaseAI.OnBodyDamaged
[Error  :   BepInEx] Could not load [ChillDrone 2.0.2] because it has missing dependencies: com.Chen.ChensGradiusMod (v3.4.3 or newer)
```
 quick error here, log will be attached below
[LogOutput.log](https://github.com/cheeeeeeeeeen/RoR2-ChensHelpers/files/6871673/LogOutput.log)

**Comment by VaelophisNyx** [comment]
to clarify about the chill drone; I grabbed the latest available release of Gradius from Thunderstore along side it. Unsure why it's outdated

EDIT: Actually, it appears I did not actually grab it...oof.
that aside, there is still the error about this mod in particular.

**Comment by GalacticRuler** [comment]
unrelated to the error I've highlighted: A bunch of items, modded and vanilla, are re-locked now despite having their unlocks complete. I was wondering if there's anything in the log that may show why? No configs I could find have anything about it

**Comment by cheeeeeeeeeen** [comment]
It all loads up fine for me. There's probably bad versions that are being loaded. I updated most my mods when ChensHelpers does get an update.

@GalacticRuler I'm sorry I didn't get to this.

**Comment by cheeeeeeeeeen** [comment]
Please say so if you have resolved the issue.
