### ISSUE TITLE
Potential Skills++ Conflict

### ISSUE THREAD

**Issue by Delta4Phoenix** [cheeeeeeeeeen/RoR2-ChensHelpers#4]
### Describe the Bug
Then used with Skills++, Skills++ does not work, always displaying the 'Buy' icon, yet never letting you buy a upgrade.

### To Reproduce
Run Chen's mods together with Skills++

### Expected Behavior
The mod to not break.

### Console Log
[message.txt](https://github.com/cheeeeeeeeeen/RoR2-ChensHelpers/files/8456211/message.txt)

### Additional Context
Note: The issue does not always appear, but it always fixed by removing Chen's mods.
Note: My Discord is Delta4Phoenix#1549 if you want to talk and work it out with me
![grafik](https://user-images.githubusercontent.com/36764081/162555586-4dd7f624-8ad4-4613-98d6-cdf704c42780.png)

**Comment by cheeeeeeeeeen** [comment]
I believe the issue is with SkillsPlusPlus. I'll talk to you in Discord then.

However, another maintainer
should be able to fix this problem as I am not modding anymore.
